TST: added IGRF unit tests
victoriyaforsythe/PyIRI pull request #39
Opened 2023-11-17 19:27 UTC by aburrell

# Description

Addresses #5 by adding some unit tests and enabling this testing in the CI.

# Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Ran unit tests locally.

`python -m pytest`

**Test Configuration**:
* Operating system: OS X Big Sur
* Version number: Python 3.9
* Any details about your local setup that are relevant

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes
- [x] Update zenodo.json file for new code contributors

2023-11-17 20:57 UTC, aburrell commented
@jklenzing could you look at how I set up coveralls maybe see why some of the tests are failing?  I tried fixing it, but without success 🐛

2023-11-21 16:02 UTC, jklenzing reviewed
I don't see anything that leaps out at met as wrong compared to how we've set up the tests elsewhere. My first thought is whether this is on the server side. ~~Have you tried re-running the tests in case coveralls was down temporarily?~~

EDIT: just saw the multiple actions that failed for the pull, but not push. develop is working as expected.

2023-11-21 16:38 UTC, aburrell commented on pyproject.toml
> +  "pytest-ordering"
It was 🐱 will delete and rerun!

2023-11-21 16:38 UTC, aburrell commented on pyproject.toml
> +  "pytest-ordering"
```suggestion
```

2023-11-21 20:18 UTC, jklenzing commented
Could be coveralls / package related. Similar issues with the push being fine and the pull mostly failing at https://github.com/pysat/pysatNASA/pull/214

2023-11-27 18:18 UTC, aburrell commented
Your new fix worked @jklenzing! 😸

2023-11-27 18:35 UTC, jklenzing requested changes

2023-11-27 18:35 UTC, jklenzing commented on PyIRI/tests/test_igrf_lib.py
> +        """Clean up all tests."""
```suggestion
        """Clean up after every test."""
```

2023-11-27 18:39 UTC, jklenzing approved these changes

2023-11-27 18:40 UTC, merged